[tool.poetry]
name = "mana-pizza"
version = "1.1.0"
description = "Mana-smoothing algorythm library meant for 2+ colors EDH decks."
authors = ["Flavio Teixeira <flavio.mtps@gmail.com>"]
readme = "README.md"
packages = [{include = "mana_pizza"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "2.31.0"
boto3 = "^1.34.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
